# Generated by Django 2.2.4 on 2019-09-23 19:38

from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_street', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business_address_link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Address')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', payment.models.Custom_date_time_field()),
                ('number_of_payments', models.IntegerField()),
                ('payment_form', models.CharField(max_length=100)),
                ('nature_of_payment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('profile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Person_payment_information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_address_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Business_address_link')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Payment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Person')),
            ],
        ),
    ]
